repos:
- hooks:
  - id: check-added-large-files
  - id: detect-private-key
  - id: fix-byte-order-marker
  - id: fix-encoding-pragma
  - id: trailing-whitespace
  repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.3.0
- hooks:
  - args:
    - --diff
    - --check
    id: black
  repo: https://github.com/psf/black
  rev: 22.3.0
- hooks:
  - id: flake8
  repo: https://gitlab.com/pycqa/flake8
  rev: 4.0.1
- hooks:
  - id: commitizen
  repo: https://github.com/commitizen-tools/commitizen
  rev: v2.29.5
