repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
    - id: check-added-large-files # prevents adding large files
    - id: detect-private-key # detects private keys
    - id: fix-byte-order-marker # fixes BOM
    - id: fix-encoding-pragma # fixes encoding pragma
    - id: no-commit-to-branch # prevents committing to protected branches
    - id: trailing-whitespace # prevents trailing whitespace
-   repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
    - id: black
      args: [--diff, --check]
-   repo: https://gitlab.com/pycqa/flake8
    rev: 4.0.1
    hooks:
    - id: flake8
-   repo: https://github.com/pycqa/pylint
    rev: v2.13.3
    hooks:
    - id: pylint
      args: [--rcfile=.pylintrc, plurall_data_jobs/]
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.942
    hooks:
    -   id: mypy
        verbose: true